# Generated by Django 2.2.1 on 2019-05-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190518_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
