# Generated by Django 2.2.1 on 2019-05-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='test',
        ),
    ]
