# Generated by Django 2.2.1 on 2019-05-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_instauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instauser',
            old_name='bio',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='user',
        ),
        migrations.AddField(
            model_name='instauser',
            name='user_email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.InstaUser'),
        ),
    ]
