# Generated by Django 2.2.1 on 2019-05-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='defaultprofile.jpeg', upload_to='images/')),
                ('profile_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.TextField()),
                ('image_comments', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('photo_image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_instagram.Profile')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
