# Generated by Django 2.2.1 on 2019-05-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_date',
        ),
    ]
